version: "3.7"
services:
    app:
        build:
            args:
                user: bank_paradise
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: bank_paradise
        container_name: bank_paradise-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - bank_paradise
        depends_on:
            - db
        command: sh -c "php artisan migrate && php-fpm"
    db:
        image: mysql
        container_name: bank_paradise-db
        restart: always
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks:
            - bank_paradise
    websockets:
        image: bank_paradise
        command: ["php", "artisan", "websockets:serve"]
        container_name: bank_paradise-websockets
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        ports:
            - 6001:6001
        networks:
            - bank_paradise
        depends_on:
            - app
            - db
    nginx:
        image: nginx:alpine
        container_name: bank_paradise-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - bank_paradise
        depends_on:
            - app
            - db

networks:
    bank_paradise:
        driver: bridge
