on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: composer install --no-scripts --no-progress --prefer-dist

      - name: Run syntax check
        run: |
          find . -name "*.php" -not -path "./vendor/*" -type f -exec sh -c 'php -l "{}" || echo "Error in file: {}"' \; 2>&1 | grep -v "No syntax errors detected" && exit 1

      - name: Pull code and deploy
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/root/bank-paradise/backend
            git pull origin main
            docker-compose exec -T app sudo composer install --optimize-autoloader --no-dev --no-interaction
            docker-compose exec -T app php artisan migrate --force
