on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # echo secrets
      - name: echo secrets
        run: |
          echo ${{ secrets.HOST }}
          echo ${{ secrets.USERNAME }}
          echo ${{ secrets.PASSWORD }}
          echo ${{ secrets.PORT }}
          echo ${{ secrets }}
          echo ${{ secrets.DEPLOY }}
      - name: pull code from github repo
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/root/bank-paradise/backend
            git pull origin main
            docker-compose down
            docker-compose up -d
