on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: echo the value of the secret
        run: echo ${{ secrets.HOST }}
      - name: pull code from github repo
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd /home/root/bank-paradise/backend
            git pull origin main
            docker-compose down
            docker-compose up -d
